const express = require("express")
const config = require('dotenv').config()
const app = express()
app.get("/",(req,res)=>res.send("Hello"))
app.listen(process.env.PORT,()=>console.log("Server Running"))